##
## EPITECH PROJECT
## GROUNDHOG
## File description:
## MAKEFILE
##

RM =	rm -f

NAME =	zappy_ai

$(NAME):
	cp main.py $@
	chmod +x $@

all: $(NAME)

clean:

fclean: clean
	$(RM) $(NAME)

re: fclean all

.PHONY: all clean fclean re